/*DATAMIGRATION A707DF04-6B97-4885-ABF8-385E54489A9A*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Bookstore', 'Book';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Book', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Book', 'Inserted', 'datetime2(3)';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Book', 'CreatedAt', 'datetime2(3)';
GO

-- ... write the data migration queries here (don't forget to use the underscore '_' in schema name) ...
UPDATE _Bookstore.Book
SET 
CreatedAt = Inserted
WHERE CreatedAt IS NULL;

EXEC Rhetos.DataMigrationApplyMultiple 'Bookstore', 'Book', 'ID, CreatedAt';